#!/bin/sh
RESOLV_CONF="/etc/resolv.conf"
[ -n "$1" ] || exit 1
NETMASK=""
[ -n "$subnet" ] && NETMASK="netmask $subnet"
case "$1" in
    deconfig) ifconfig $interface 0.0.0.0 ;;
    renew|bound)
        ifconfig $interface $ip $NETMASK
        [ -n "$router" ] && route add default gw $router
        > "$RESOLV_CONF"
        for i in $dns; do echo "nameserver $i" >> "$RESOLV_CONF"; done
        ;;
esac
